apiVersion: apps/v1
kind: Deployment
metadata:
  name: mock-server-api-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mock-server-api
  template:
    metadata:
      labels:
        app: mock-server-api
    spec:
      volumes:
        - name: mock-server-api-volume
          persistentVolumeClaim:
            claimName: mock-server-api-pvc
      containers:
        - name: mock-server-api-container
          image: innovadeveloper/mock-server-api:latest
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: mock-server-api-volume
              mountPath: /data/
