apiVersion: v1
kind: PersistentVolume
metadata:
  name: mock-server-api-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    # path: ./../assets/
    path: /Users/kennybaltazaralanoca/Projects/NodeProjects/mock-server-project/assets/