apiVersion: v1
kind: Service
metadata:
  name: mock-server-api-service
spec:
  type: NodePort
  selector:
    app: mock-server-api  #Las etiquetas de selector que coinciden con las del Deployment para indicar qué Pods deben exponerse a través del servicio.
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30000