apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kenny-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin # view
subjects:
- kind: User
  name: kenny-admin    
# kubectl get secrets -n <nombre-del-namespace> | grep <nombre-del-usuario>-token
# kubectl get secrets grep kenny-admin-token
